### PR TITLE
Generate examples

### PR DESCRIPTION
**Pull request by timkendrick**
This adds a script to generate example markdown files as follows:

```javascript
node examples/generate.js
```

I put some basic headers in the template, but these can easily be changed.

### CODE REVIEW

**Comment by timkendrick** [comment]
Oh crap, just realized there's already an `examples/generate.sh` script in there. My bad. Probably best to use the shell script to generate the examples, seeing as it's much simpler than my one.

**Comment by faceleg** [comment]
Do they generate the same output?

**Comment by timkendrick** [comment]
The only difference in the output is that my one inserts headers for the different sections (which could easily be removed, or likewise added into the shell script version).

My version also gives a little more information on the progress, but similarly this would be trivial either to remove or add to the shell script version.

There's basically no difference between them, so I'd say go for the shell script version because it's much simpler (unless you want to speed it up further down the line by hooking into the JS library directly rather than spawning two child processes for each example – this would be kind of pointless in the grand scheme of things though)

**Comment by faceleg** [comment]
I'm sorry that you had to do all this work for nothing then :(

**Comment by timkendrick** [comment]
Serves me right for not checking (and choosing the wrong tool for the job)!

I've added PR #27 that fixes the shell script version and updates the example docs.

**Comment by faceleg** [comment]
Already merged

**Comment by timkendrick** [comment]
:+1:

**Pull request closed without merging**
